name: Update Repository

on:
  push:
      paths: 
        - 'release-versions/*'
        
jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - name: Get release
        id: get_release
        uses: cardinalby/git-get-release-action@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          latest: true

      - name: Create JSON
        uses: jsdaniell/create-json@v1.2.2
        with:
          name: repo.json
          json: '{"META": {"repoName": "uYouPlus-Extra Repo","repoIcon": "https://user-images.githubusercontent.com/78001398/271790092-006e81cc-715a-4fbc-aff6-15832e2da8c4.png"},"Tweaked": [{"name": "uYou+-Extra","icon": "https://user-images.githubusercontent.com/78001398/271790092-006e81cc-715a-4fbc-aff6-15832e2da8c4.png","version": steps.get_release.outputs.tag_name,"down": steps.get_release.outputs.assets_url,"category": "Tweaked Apps","description": "uYou+-Extra is a modified version of uYou (made by @MiRO92) with additional features and mainly made for non jailbroken users!","bundleID": "com.google.ios.youtube","appstore": "com.google.ios.youtube","screenshots": ["https://user-images.githubusercontent.com/52943116/189822859-8a0952db-9264-4b5b-9cbe-d0a87b2db5a0.PNG"],"contact": "https://github.com/arichorn/uYouPlusExtra"}]}'
