name: Update Repository

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      manual_trigger:
        description: 'Manual trigger'
        required: false
        
jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Get release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          echo "VERSION=$(curl -s -H "Authorization: token $GITHUB_TOKEN" "https://api.github.com/repos/arichorn/uYouPlusExtra/releases/latest" | jq -r '.tag_name')" >> $GITHUB_ENV
          echo "ASSET_URL=$(curl -s -H "Authorization: token $GITHUB_TOKEN" "https://api.github.com/repos/arichorn/uYouPlusExtra/releases/latest" | jq -r '.assets[0].browser_download_url')" >> $GITHUB_ENV

      - name: Check if version is newer
        id: check_condition
        run: echo "NEW=$([[ "$(jq -r .Tweaked[0].version repo.json)" != env.VERSION ]] && echo "true" || echo "false")" >> $GITHUB_ENV
      
      - name: Create JSON
        uses: jsdaniell/create-json@v1.2.2
        if: env.NEW == 'true'
        with:
          name: repo.json
          json: '{"META": {"repoName": "uYouPlus-Extra Repo","repoIcon": "https://user-images.githubusercontent.com/78001398/271790092-006e81cc-715a-4fbc-aff6-15832e2da8c4.png"},"Tweaked": [{"name": "uYou+-Extra","icon": "https://user-images.githubusercontent.com/78001398/271790092-006e81cc-715a-4fbc-aff6-15832e2da8c4.png","version": "${{ env.VERSION }}","down": "${{ env.ASSET_URL }}","category": "Tweaked Apps","description": "uYou+-Extra is a modified version of uYou (made by @MiRO92) with additional features and mainly made for non jailbroken users!","bundleID": "com.google.ios.youtube","appstore": "com.google.ios.youtube","screenshots": ["https://user-images.githubusercontent.com/52943116/189822859-8a0952db-9264-4b5b-9cbe-d0a87b2db5a0.PNG"],"contact": "https://github.com/arichorn/uYouPlusExtra"}]}'

      - run: cat repo.json
        if: env.NEW == 'true'
      
      - name: Commit new file
        if: env.NEW == 'true'
        run: |
          git config --global user.name "niels-beier"
          git config --global user.email "shuzoyt@arcor.de"
          git add .
          git commit -am "Auto updating to $(env.VERSION) of uYouPlusExtra"
          git push
